import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Note } from '../index';

const NotesPage = () => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [notes, setNotes] = useState<Note[]>([]);
  const router = useRouter();

  const getNotes = async () => {
    try {
      const notes_data = await fetch('http://localhost:8000/api/notes/');
      const notes_json = await notes_data.json();
      const notes = notes_json;

      if (notes) {
        setNotes(notes);
      } else {
        setNotes([]);
      }
    } catch (error) {
      console.log(error + 'Error fetching data from /api/notes/');
    }
  };

  useEffect(() => {
    // Check if user is authenticated
    if (localStorage.getItem('token')) {
      setIsAuthenticated(true);
      getNotes();
    } else {
      router.push('/login');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Life-Kitz | Notes Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isAuthenticated ? (
        <>
          <h1>Notes</h1>
          <ul>
            {!notes ? (
              notes.map((note) => (
                <li key={note.id}>
                  <h2>{note.title}</h2>
                  <p>{note.content}</p>
                </li>
              ))
            ) : (
              <p>No notes yet</p>
            )}
          </ul>
        </>
      ) : (
        <p>Loading...</p>
      )}
    </>
  );
};

export default NotesPage;
