# Generated by Django 4.2 on 2023-04-04 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
