import Head from "next/head";

interface HomePageProps {
  message: string;
}

const HomePage: React.FC<HomePageProps> = ({ message }) => {
  return (
    <>
      <Head>
        <title>Life-Kitz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Life-Kitz</h1>
        <div>
          <p>
            Life-Kitz is a web application that helps you keep track of your
            life.
          </p>
          <p>{message}</p>
        </div>
      </main>
    </>
  );
};

export async function getServerSideProps() {
  return {
    props: {
      // props for your component
      message: "Hello World",
    },
  };
}

export default HomePage;
